# Generated by Django 4.1.7 on 2023-02-25 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_pics', models.FileField(upload_to='profile')),
                ('role', models.CharField(choices=[('examiner', 'examiner'), ('teacher', 'teacher'), ('student', 'student')], default='teacher', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('access_code', models.CharField(max_length=9)),
                ('be_examiner', models.BooleanField(default=False)),
                ('administrator', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
