# Generated by Django 4.1.7 on 2023-02-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_initial'),
        ('teacher_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_profile',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.district'),
        ),
        migrations.AddField(
            model_name='teacher_profile',
            name='local_government',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.local_government'),
        ),
    ]
