# Generated by Django 4.1.7 on 2023-02-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_panel', '0002_teacher_profile_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_profile',
            name='verified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
