# Generated by Django 4.1.7 on 2023-02-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_panel', '0003_alter_teacher_profile_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_profile',
            name='profile_pics',
            field=models.ImageField(upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='teacher_profile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
