# Generated by Django 4.2 on 2023-04-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_panel', '0004_alter_teacher_profile_profile_pics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_profile',
            name='date_of_birth',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teacher_profile',
            name='gender',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher_profile',
            name='latitude',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='teacher_profile',
            name='longitude',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
