# Generated by Django 4.2 on 2023-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_panel', '0005_teacher_profile_date_of_birth_teacher_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_profile',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher_profile',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_profile',
            name='latitude',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_profile',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_profile',
            name='verified_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
