# Generated by Django 4.2 on 2023-04-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_panel', '0006_alter_teacher_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('avatar', models.ImageField(upload_to='profile')),
                ('date_of_birth', models.DateField(null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_level', models.CharField(choices=[('junior', 'junior'), ('senior', 'senior')], default='junior', max_length=6)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(upload_to='profile')),
                ('remove', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher_profile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='teacher_profile',
            name='local_government',
        ),
        migrations.RemoveField(
            model_name='teacher_profile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='teacher_profile',
            name='user',
        ),
    ]
