# Generated by Django 4.1.7 on 2023-02-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter the name of the competition which will display physically.', max_length=80)),
                ('description', models.TextField(help_text='give brief explanation of the competition.')),
                ('exam_status', models.CharField(choices=[('not started', 'not started'), ('started', 'started'), ('ended', 'ended')], default='not started', help_text="don't edited this until you know what you are doing.", max_length=11)),
                ('exam_duration', models.DurationField()),
                ('custom_link_slug', models.CharField(max_length=100)),
                ('can_join_with_link', models.BooleanField(default=False)),
                ('request_password_when_using_link', models.BooleanField(default=True)),
                ('number_of_allowed_attempt', models.IntegerField(default=1)),
                ('joining_password', models.CharField(max_length=20)),
                ('starting_at', models.DateTimeField()),
                ('ending_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local_Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_of_school', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=7)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
