# Generated by Django 4.1.7 on 2023-02-25 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher_panel', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='school_admintrator', to='teacher_panel.teacher_profile'),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.district'),
        ),
        migrations.AddField(
            model_name='school',
            name='local_government',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.local_government'),
        ),
        migrations.AddField(
            model_name='district',
            name='local_government',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='general.local_government'),
        ),
    ]
