# Generated by Django 4.2 on 2023-04-22 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_rename_local_government_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='zone',
        ),
        migrations.AddField(
            model_name='zone',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='general.district'),
        ),
    ]
